parameters:
  bazinga.jstranslation.translation_finder.class: Bazinga\Bundle\JsTranslationBundle\Finder\TranslationFinder
  bazinga.jstranslation.translation_dumper.class: Bazinga\Bundle\JsTranslationBundle\Dumper\TranslationDumper

services:
  bazinga.jstranslation.translation_finder:
    class: "%bazinga.jstranslation.translation_finder.class%"
    arguments: ['collection']
  bazinga.jstranslation.translation_dumper:
    class: "%bazinga.jstranslation.translation_dumper.class%"
    arguments:
      - '@templating'
      - "@bazinga.jstranslation.translation_finder"
      - "@router"
      - "@filesystem"
      - "@=service('translator').getLocal()"
      -
      -
      -